# source 'https://rubygems.org'
source 'http://ruby.taobao.org'

gem 'rails', '3.2.8'
gem 'jquery-rails', '2.0.2'
gem 'pg', '0.12.2'
gem 'bootstrap-sass', '2.0.4'
gem 'bcrypt-ruby', '3.0.1'

group :assets do
  gem 'sass-rails', '3.2.5'
  gem 'coffee-rails', '3.2.2'
  gem 'uglifier', '1.2.3'
end

group :development, :test do
  gem 'sqlite3', '1.3.5'
  gem 'rspec-rails', '2.11.0'
  gem 'annotate', '~> 2.4.1.beta'
  gem 'guard-rspec', '1.2.1'
  gem 'guard-spork', :github => 'guard/guard-spork'
  gem 'spork', '0.9.2'

end

group :test do
  gem 'capybara', '1.1.2'
  gem 'rb-inotify', '~> 0.9'
  gem 'libnotify', '0.5.9'
  gem 'factory_girl_rails', '4.1.0'
end

# group :production do
  # gem 'pg', '0.12.2'
# end